# Generated by Django 6.0.3 on 2026-03-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_sale_customer_attendant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='martial_art_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_sku',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
