# Generated by Django 6.0.3 on 2026-03-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_alter_product_martial_art_type_alter_product_sku_and_more'),
        ('pos', '0004_stockadjustment'),
    ]

    operations = [
    ]
