# Generated by Django 6.0.4 on 2026-04-14 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_tenant_rename_martial_art_type_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.tenant'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.tenant'),
        ),
    ]
