# Generated by Django 6.0.4 on 2026-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_alter_product_tenant_alter_sale_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#7c3aed', max_length=7),
        ),
    ]
