# Generated by Django 6.0.4 on 2026-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_tenant_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='icon',
            field=models.CharField(default='🏪', max_length=10),
        ),
    ]
