# Generated by Django 6.0.3 on 2026-06-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_stockadjustment_remove_teste'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='pv_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['tenant', 'created_at'], name='sale_tenant_created_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['created_at'], name='stockadj_created_idx'),
        ),
    ]
